-- TOC Smithton Control: Supabase security for central settings
-- Run this once in the Supabase SQL Editor.

-- Ensure the single central settings row exists.
INSERT INTO public.control_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- Public users may read the central settings.
DROP POLICY IF EXISTS "control_settings_public_read" ON public.control_settings;
CREATE POLICY "control_settings_public_read"
ON public.control_settings
FOR SELECT
TO anon, authenticated
USING (true);

-- Only users listed in admin_users may change central settings.
DROP POLICY IF EXISTS "control_settings_admin_update" ON public.control_settings;
CREATE POLICY "control_settings_admin_update"
ON public.control_settings
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE admin_users.user_id = auth.uid()
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.admin_users
    WHERE admin_users.user_id = auth.uid()
  )
);

-- Do not allow browser users to insert or delete central settings.
DROP POLICY IF EXISTS "control_settings_no_insert" ON public.control_settings;
DROP POLICY IF EXISTS "control_settings_no_delete" ON public.control_settings;


-- Manual environmental readings are centrally stored so public control pages are read-only.
CREATE TABLE IF NOT EXISTS public.manual_control_readings (
  id bigint generated by default as identity primary key,
  location text NOT NULL,
  zone text NOT NULL DEFAULT 'default',
  salinity numeric,
  reading_time timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id),
  UNIQUE(location, zone)
);

ALTER TABLE public.manual_control_readings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "manual_control_readings_public_read" ON public.manual_control_readings;
CREATE POLICY "manual_control_readings_public_read"
ON public.manual_control_readings
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "manual_control_readings_admin_insert" ON public.manual_control_readings;
CREATE POLICY "manual_control_readings_admin_insert"
ON public.manual_control_readings
FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid()));

DROP POLICY IF EXISTS "manual_control_readings_admin_update" ON public.manual_control_readings;
CREATE POLICY "manual_control_readings_admin_update"
ON public.manual_control_readings
FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid()));


-- Pittwater 48-hour salinity reopening records. Public read-only; admins may enter/update.
CREATE TABLE IF NOT EXISTS public.pittwater_48h_salinity (
  id bigint generated by default as identity primary key,
  zone text NOT NULL,
  check_point text NOT NULL CHECK (check_point IN ('T0','T24','T48')),
  salinity numeric,
  reading_date date,
  reading_time time,
  low_tide boolean NOT NULL DEFAULT false,
  sampling_officer text,
  source text,
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES auth.users(id),
  UNIQUE(zone, check_point)
);
ALTER TABLE public.pittwater_48h_salinity ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pittwater_48h_salinity_public_read" ON public.pittwater_48h_salinity;
CREATE POLICY "pittwater_48h_salinity_public_read" ON public.pittwater_48h_salinity FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "pittwater_48h_salinity_admin_insert" ON public.pittwater_48h_salinity;
CREATE POLICY "pittwater_48h_salinity_admin_insert" ON public.pittwater_48h_salinity FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid()));
DROP POLICY IF EXISTS "pittwater_48h_salinity_admin_update" ON public.pittwater_48h_salinity;
CREATE POLICY "pittwater_48h_salinity_admin_update" ON public.pittwater_48h_salinity FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users WHERE admin_users.user_id = auth.uid()));
